---
title: "Dim1UniformExperiments"
author: "Anirban Chatterjee"
date: '2023-01-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/Dropbox (Penn)/Kernel-Two-Sample/Simulations/Revision Simulations/Revision II Simulations/Oracle Split MMD/Oracle Tests/MMDAgg-Paper')
```

```{r}
library(reticulate)

reticulate::conda_install(
    packages = c("cvxopt", "scikit-learn"),
)

reticulate::conda_install(packages = "numba")

reticulate::py_install(
  packages = c("numpy", "numba", "pandas", "scipy", "torch",
                "dataframe_image", "matplotlib"),
  pip = TRUE
)
```

```{python}
"""
Running this script creates two files results.csv and results.plk in 
the 'user/raw' directory containing the relevant parameters and the estimated 
power/level of the tests. We use the following numbering of experiments: 
uniform mnist 
   1      2      
   3      4
   5      6
   7      8
   9      10
   11     12
Experiments i and i+1 are the same but using the uniform and mnist data.
We first run the uniform experiments followed by the mnist experiments.
The settings of all those experiments can be understood by their 
relations to the figures presented in our paper:
Figure 3 and 4: experiments 1 and 3
Figure 5: experiments 2 and 4
Figure 6: experiments 9 and 10
Figure 7: experiments 1, 2, 3 and 4
Figure 8: experiments 7 and 8
Figure 9: experiments 1, 2, 11 and 12
Table 1: experiments 5 and 6
The figures and table can be created by running the figures.py script.
"""

import numpy as np
import itertools
import pandas as pd
from mnist import download_mnist, load_mnist
from pathlib import Path
from seed import generate_seed
from sample_test import sample_and_test_uniform, sample_and_test_mnist
import argparse

# create results directory if it does not exist
Path("user/raw").mkdir(exist_ok=True, parents=True)

# panda dataframe: lists of indices and entries
index_vals = []
results = []

# parameters shared for all experiments
alpha = 0.05
B1 = 500
B2 = 500
B3 = 100
kernel_types = ["gaussian", "laplace"]
k_num = len(kernel_types)
approx_types = ["wild bootstrap"]
a_num = len(approx_types)

############# UNIFORM #############
# parameters for all uniform experiments
s = 1
perturbation_multipliers = [2.7]
bandwidth_multipliers = np.linspace(0.1, 2, 20)
e_num = 1
p_num = 6

# Experiment 1
exp = "3: uniform alternative"
repetitions = 500
sample_sizes = [500]
l_minus = l_plus = None
l_minus_l_plus = None
function_types = ["split", "split (doubled sample sizes)"]
f_num = len(function_types)

for a, k, e, f, p in itertools.product(
    range(a_num), range(k_num), range(e_num), range(f_num), range(p_num)
):
    print (k,p)
    if (e, p) != (1, 3):
        approx_type = approx_types[a]
        kernel_type = kernel_types[k]
        d = e + 1
        n = m = sample_sizes[e]
        perturbation_multiplier = perturbation_multipliers[e]
        function_type = function_types[f]
        perturbation = p + 1
        perturbation_or_Qi = perturbation
        test_output_list = []
        for i in range(repetitions):
            seed = generate_seed(k, e, 3, f, p, i)
            test_output_list.append(
                sample_and_test_uniform(
                    function_type,
                    seed,
                    kernel_type,
                    approx_type,
                    m,
                    n,
                    d,
                    perturbation,
                    s,
                    perturbation_multiplier,
                    alpha,
                    l_minus,
                    l_plus,
                    B1,
                    B2,
                    B3,
                    bandwidth_multipliers,
                )
            )
        power = np.mean(test_output_list)
        index_val = (
            exp,
            d,
            repetitions,
            m,
            n,
            approx_type,
            kernel_type,
            l_minus_l_plus,
            function_type,
            perturbation_or_Qi,
        )
        index_vals.append(index_val)
        results.append(power)
print('Experiment 3 completed.')

# save panda dataframe
index_names = (
    "experiment",
    "d",
    "repetitions",
    "m",
    "n",
    "approx_type",
    "kernel_type",
    "l_minus_l_plus",
    "function_type",
    "perturbation_or_Qi",
)
index = pd.MultiIndex.from_tuples(index_vals, names=index_names)
results_df = pd.Series(results, index=index).to_frame("power")
results_df.reset_index().to_csv("user/raw/results.csv")
```

```{r}
index_vals.r <- py$index_vals
results.r <- py$results
```